language: cpp
dist: bionic

compiler:
  - clang

install:    
  - |
    wget https://cmake.org/files/v3.17/cmake-3.17.0-rc3-Linux-x86_64.tar.gz
    tar -xf	cmake-3.17.0-rc3-Linux-x86_64.tar.gz
    sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.17.0-rc3-Linux-x86_64/bin/cmake /home/travis/bin/cmake
    sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.17.0-rc3-Linux-x86_64/bin/ctest /home/travis/bin/ctest

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
