language: cpp

dist: bionic

arch:
  - amd64
  - arm64

compiler:
  - gcc
  - clang

before_install: 
  - sudo apt-get -y install mosquitto
  - sudo apt-get -y install mosquitto-clients

install:
  - |
    wget https://cmake.org/files/v3.17/cmake-3.17.0-rc3-Linux-x86_64.tar.gz
    tar -xf	cmake-3.17.0-rc3-Linux-x86_64.tar.gz
    sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.17.0-rc3-Linux-x86_64/bin/cmake /home/travis/bin/cmake
    sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.17.0-rc3-Linux-x86_64/bin/ctest /home/travis/bin/ctest
  - |
    qres=$(dpkg -s libcbor 2>/dev/null | grep "Status" | tr -d ' ')
    if [ -z $qres ]; then
        wget https://github.com/PJK/libcbor/archive/v0.5.0.zip
        unzip v0.5.0.zip
        cd libcbor-0.5.0
        cmake CMakeLists.txt
        make
        sudo make install
        cd ..
    else
        echo "libcbor already installed..."
    fi
    
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - make test
