language: cpp

dist: bionic

arch:
  - amd64

compiler:
  - clang

before_install: 
  - sudo apt-get -y install mosquitto
  - sudo apt-get -y install mosquitto-clients
  - sudo apt-get -y install libboost-all-dev
  - sudo apt-get -y install libevent-dev
  - sudo apt-get -y install libhiredis-dev
  - |
    wget https://cmake.org/files/v3.17/cmake-3.17.0-rc3-Linux-x86_64.tar.gz
    tar -xf	cmake-3.17.0-rc3-Linux-x86_64.tar.gz
    sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.17.0-rc3-Linux-x86_64/bin/cmake /home/travis/bin/cmake
    sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.17.0-rc3-Linux-x86_64/bin/ctest /home/travis/bin/ctest
  - |
    qres=$(ldconfig -p | grep mqtt3a | tr -d ' ')
    if [ -z $qres ]; then
        wget -O mqtt.tar.gz https://github.com/eclipse/paho.mqtt.c/archive/v1.3.0.tar.gz
        tar xvzf mqtt.tar.gz
        cd paho.mqtt.c-1.3.0
        make
        sudo make install
        cd ..
    fi

before_script:
  - mkdir build
  - cd build
  - cmake -DJAMSCRIPT_ON_TRAVIS_OPT=ON ..

script:
  - make
  - cd test
  - ./test-main
