name: JAMSched C/C++ CI

on:
  push:
    branches: [ master, arm-rasp-dev-1 ]
  pull_request:
    branches: [ master, arm-rasp-dev-1 ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
